version: "3"

services: 
    db:
        image: postgres:12
        container_name: economyflow_db
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - economyflow-db:/var/lib/postgresql/data
    server:
        container_name: economyflow_server
        image: economyflow:dev
        environment:
            - DJANGO_SETTINGS_MODULE:economyflow.settings.dev
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        depends_on: 
            - db
volumes: 
    economyflow-db: