version: "3"

services: 
    db:
        image: postgres:12
        container_name: economyflow_db
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - economyflow-db:/var/lib/postgresql/data
    server:
        container_name: economyflow_server
        image: docker.pkg.github.com/mubarak117136/economyflow/economyflow:prod
        environment:
            - DJANGO_SETTINGS_MODULE:economyflow.settings.production
        command: gunicorn -w 10 -b unix:/app/server/socket/ECONOMYFLOW.sock economyflow.wsgi:application
        volumes:
            - ./server/.env:/app/server/.env
            - ./server/static:/app/server/static
            - ./server/media:/app/server/media
            - ./server/socket:/app/server/socket
volumes: 
    economyflow-db: