# Generated by Django 3.1.7 on 2021-04-27 14:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_evestpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='evestpage',
            name='body',
            field=wagtail.core.fields.StreamField([('evest_left', wagtail.core.blocks.StructBlock([('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('youtube_video', wagtail.core.blocks.URLBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
