# Generated by Django 3.1.7 on 2021-04-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_apiregistration_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiregistration',
            name='type',
            field=models.CharField(choices=[('evest', 'Evest')], default='evest', max_length=50),
        ),
    ]
