# Generated by Django 3.1.7 on 2021-04-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210427_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiregistration',
            name='type',
            field=models.CharField(choices=[('Evest', 'evest')], default='Evest', max_length=50),
        ),
    ]
