# Generated by Django 3.1.7 on 2021-04-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210427_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sign_up_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='apiregistration',
            name='type',
            field=models.CharField(choices=[('Evest', 'evest'), ('Trade360', 'trade360')], default='Evest', max_length=50),
        ),
    ]
