# Generated by Django 3.1.7 on 2021-04-29 14:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0013_userprofile_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade360',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('form_title', models.CharField(blank=True, max_length=255, null=True)),
                ('firstName_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('email_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('password_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('country_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('submit_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('body', wagtail.core.fields.StreamField([('trade360_head_right', wagtail.core.blocks.StreamBlock([('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('youtube_video', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
