# Generated by Django 3.1.7 on 2021-04-30 07:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0014_trade360'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evestpage',
            name='form_subtitle',
        ),
        migrations.AddField(
            model_name='evestpage',
            name='form_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='evestpage',
            name='body',
            field=wagtail.core.fields.StreamField([('evest_left', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade360',
            name='body',
            field=wagtail.core.fields.StreamField([('trade360_head_right', wagtail.core.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock()), ('background_img', wagtail.images.blocks.ImageChooserBlock()), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=True))])), ('trade360_three_column_block', wagtail.core.blocks.StructBlock([('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.CharBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
