# Generated by Django 3.1.7 on 2021-04-30 09:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0015_auto_20210430_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiregistration',
            name='type',
            field=models.CharField(choices=[('Evest', 'evest'), ('Trade360', 'trade360'), ('LegacyFx', 'legacyfx')], default='Evest', max_length=50),
        ),
        migrations.AlterField(
            model_name='evestpage',
            name='body',
            field=wagtail.core.fields.StreamField([('evest_left', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('img', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock())])), ('why_evest', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))]))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LegacyFxPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('form_title', models.CharField(blank=True, max_length=255, null=True)),
                ('email_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('password_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('firstName_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('country_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('submit_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
