# Generated by Django 3.1.7 on 2021-04-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210430_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='evestpage',
            name='parameters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
