# Generated by Django 3.1.7 on 2021-05-04 18:24

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_collectionpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiregistration',
            name='type',
            field=models.CharField(choices=[('evest', 'Evest'), ('trade360', 'Trade360'), ('legacyfx', 'LegacyFx')], default='evest', max_length=50),
        ),
        migrations.AlterField(
            model_name='evestpage',
            name='body',
            field=wagtail.core.fields.StreamField([('evest_left', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('img', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock())])), ('why_evest', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))])), ('evest_title_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('description', wagtail.core.blocks.RichTextBlock())])), ('evest_title_img', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('img_desc', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('img', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
