# Generated by Django 3.1.7 on 2021-05-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210505_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='campaign',
            field=models.CharField(blank=True, default='EF03', max_length=150, null=True),
        ),
    ]
