# Generated by Django 3.1.7 on 2021-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_userprofile_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyfxpage',
            name='tag',
            field=models.CharField(blank=True, default='ashraf_channel', max_length=255, null=True),
        ),
    ]
