# Generated by Django 3.1.7 on 2021-05-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_legacyfxpage_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='evestpage',
            name='template_choice',
            field=models.CharField(choices=[('ramadan', 'Ramadan'), ('islamic', 'Islamic')], default='ramadan', max_length=100),
        ),
    ]
