# Generated by Django 3.1.7 on 2021-05-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_evestpage_template_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evestpage',
            name='template_choice',
            field=models.CharField(choices=[('ramadan', 'Ramadan'), ('islamic', 'Islamic'), ('ef05', 'Ef05')], default='ramadan', max_length=100),
        ),
    ]
