# Generated by Django 3.1.7 on 2021-05-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0024_auto_20210518_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiregistration',
            name='type',
            field=models.CharField(choices=[('evest', 'Evest'), ('trade360', 'Trade360'), ('legacyfx', 'LegacyFx'), ('ingot', 'Ingot')], default='evest', max_length=50),
        ),
        migrations.CreateModel(
            name='IngotBrokerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('form_title', models.CharField(blank=True, max_length=255, null=True)),
                ('email_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('password_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('firstName_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('country_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('submit_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
