# Generated by Django 3.1.7 on 2021-06-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0026_ingotbrokerpage_template_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlvexoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('template_choice', models.CharField(choices=[('starter-template', 'Starter Template')], default='starter-template', max_length=100)),
                ('parameters', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='legacyfxpage',
            name='password_placeholder',
        ),
        migrations.AlterField(
            model_name='evestpage',
            name='template_choice',
            field=models.CharField(choices=[('ramadan', 'Ramadan'), ('islamic', 'Islamic'), ('ef05', 'Ef05'), ('ef06', 'Ef06'), ('btcnews1', 'BTCNews1'), ('btcnews2', 'BTCNews2'), ('btcnews3', 'BTCNews3')], default='ramadan', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingotbrokerpage',
            name='template_choice',
            field=models.CharField(choices=[('camp1', 'Campaign 1'), ('camp2', 'Campaign 2')], default='camp1', max_length=100),
        ),
    ]
