# Generated by Django 3.1.7 on 2021-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210701_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='alvexopage',
            name='is_redirect_evest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alvexopage',
            name='is_redirect_legacyfx',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apiregistration',
            name='type',
            field=models.CharField(choices=[('evest', 'Evest'), ('trade360', 'Trade360'), ('legacyfx', 'LegacyFx'), ('ingot', 'Ingot'), ('alvexo', 'Alvexo')], default='evest', max_length=50),
        ),
    ]
