# Generated by Django 3.1.7 on 2021-07-03 03:15

from django.db import migrations
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210701_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='evestpage',
            name='allowed_countries',
            field=wagtail.core.fields.StreamField([('allowed_countries', wagtail.core.blocks.StructBlock([('countries', wagtail.core.blocks.ListBlock(home.blocks.Country))]))], null=True),
        ),
    ]
