# Generated by Django 3.1.7 on 2021-07-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0031_auto_20210703_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradersGCCPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('template_choice', models.CharField(choices=[('starter-template', 'Starter Template')], default='starter-template', max_length=100)),
                ('parameters', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
