# Generated by Django 3.1.7 on 2021-07-05 08:59

from django.db import migrations
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_tradersgccpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradersgccpage',
            name='redirection',
            field=wagtail.core.fields.StreamField([('redirection', wagtail.core.blocks.StructBlock([('redirect', wagtail.core.blocks.ListBlock(home.blocks.RedirectRules))]))], null=True),
        ),
    ]
