# Generated by Django 3.1.7 on 2021-07-05 12:42

from django.db import migrations, models
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20210705_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alvexopage',
            name='is_redirect_evest',
        ),
        migrations.RemoveField(
            model_name='alvexopage',
            name='is_redirect_legacyfx',
        ),
        migrations.AddField(
            model_name='alvexopage',
            name='redirection',
            field=wagtail.core.fields.StreamField([('redirection', wagtail.core.blocks.StructBlock([('redirect', wagtail.core.blocks.ListBlock(home.blocks.RedirectRules))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiregistration',
            name='type',
            field=models.CharField(choices=[('evest', 'Evest'), ('trade360', 'Trade360'), ('legacyfx', 'LegacyFx'), ('ingot', 'Ingot'), ('alvexo', 'Alvexo'), ('axia', 'Axia')], default='evest', max_length=50),
        ),
    ]
