# Generated by Django 3.1.7 on 2021-07-13 15:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0036_auto_20210705_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedirectionRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('type', models.CharField(choices=[('accepted', 'Accepted'), ('redirect', 'Redirect'), ('other', 'Other')], default='accepted', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('redirect_url', models.URLField(max_length=255)),
                ('redirect', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirection', to='home.redirection')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedirectCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=10)),
                ('rules', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirection_rules', to='home.redirectionrules')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
