# Generated by Django 3.1.7 on 2021-07-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_redirectcountries_redirection_redirectionrules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirection',
            name='page',
        ),
        migrations.AddField(
            model_name='redirection',
            name='page_type',
            field=models.CharField(choices=[('evest', 'Evest'), ('trade360', 'Trade360'), ('legacyfx', 'LegacyFx'), ('ingot', 'Ingot'), ('alvexo', 'Alvexo'), ('axia', 'Axia')], default='evest', max_length=100),
        ),
    ]
