# Generated by Django 3.1.7 on 2021-07-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_acceptedmainparam_centralredirection'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralredirection',
            name='redirect_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
