# Generated by Django 3.1.7 on 2021-07-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_centralredirection_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralredirection',
            name='accepted_param',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
