# Generated by Django 3.1.7 on 2021-09-26 18:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0045_demopage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ButtonLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('type', models.CharField(choices=[('country', 'Country'), ('other', 'Other')], default='country', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('redirect_url', models.URLField(max_length=255)),
                ('button_link', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_link', to='home.buttonrules')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ButtonCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=10)),
                ('rules', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_countries', to='home.buttonlink')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
