# Generated by Django 3.1.7 on 2021-09-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_demopage_investment_plan_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='demopage',
            name='desc',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='demopage',
            name='hero_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
