# Generated by Django 3.1.7 on 2021-09-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_demopage_reference_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demopage',
            old_name='reference_name',
            new_name='page_title',
        ),
    ]
