# Generated by Django 3.1.7 on 2021-12-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20211212_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evestpage',
            name='template_choice',
            field=models.CharField(choices=[('ramadan', 'Ramadan'), ('islamic', 'Islamic'), ('ef05', 'Ef05'), ('ef06', 'Ef06'), ('btcnews1', 'BTCNews1'), ('btcnews2', 'BTCNews2'), ('btcnews3', 'BTCNews3'), ('youtube', 'Youtube'), ('crypto', 'Crypto'), ('bitcoin', 'Bitcoin')], default='ramadan', max_length=100),
        ),
    ]
