# Generated by Django 3.1.7 on 2022-07-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20220425_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('country', models.CharField(max_length=150, verbose_name='Country')),
                ('app_name', models.CharField(max_length=250, verbose_name='App name')),
            ],
        ),
        migrations.AlterField(
            model_name='avapage',
            name='template_choice',
            field=models.CharField(choices=[('ramadan', 'Ramadan'), ('stock', 'Stock')], default='ramadan', max_length=100),
        ),
    ]
