# Generated by Django 3.1.7 on 2022-07-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20220728_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time'),
        ),
    ]
