# Generated by Django 3.1.7 on 2022-11-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_leads_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='evestpage',
            name='account_used',
            field=models.CharField(choices=[(0, 'Media Buy'), (1, 'PPC')], default=0, max_length=100),
        ),
    ]
