# Generated by Django 3.1.7 on 2022-11-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_evestpage_account_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evestpage',
            name='account_used',
            field=models.IntegerField(choices=[(0, 'Media Buy'), (1, 'PPC')], default=0),
        ),
    ]
